inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'lib/twilio-ruby/rest/**/*'
    - 'spec/integration/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 175

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Max: 20
