##
# This code was generated by
# \ / _    _  _|   _  _
#  | (_)\/(_)(_|\/| |(/_  v1.0.0
#       /       /       

module Twilio
  module REST
    class CountryList < ListResource
      ##
      # Initialize the CountryList
      def initialize(version)
        super
        
        # Path Solution
        @solution = {}
        @uri = "/Voice/Countries"
      end
      
      ##
      # Reads CountryInstance records from the API as a list.
      def read(self, limit=nil, page_size=nil)
        @version.read(
            limit,
            page_size
        ))
      end
      
      ##
      # Retrieve a single page of CountryInstance records from the API.
      def page(self, page_token=None, page_number=None, page_size=None)
        params = values.of({
            PageToken: page_token,
            Page: page_number,
            PageSize: page_size,
        })
        @version.page(
            self,
            CountryInstance,
            @solution,
            'GET',
            @uri,
            params
        )
      end
      
      ##
      # Constructs a CountryContext
      def get(iso_country)
        CountryContext.new(@version, iso_country, @solution)
      end
      
      ##
      # Provide a user friendly representation
      def to_s
        '#<Twilio.Pricing.V1.CountryList>'
      end
    end
  end
end