name: Bug report
description: Report a bug with the twilio-ruby helper library.
title: "[BUG] Describe the issue briefly"
labels: "type: bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in the twilio-ruby helper library. Please provide the details below to help us investigate and resolve the issue.

  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the issue.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code snippet
      description: Provide the code snippet that reproduces the issue.
      placeholder: "```\n// Code snippet here\n```"
    validations: 
        required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: Describe what actually happened.
      placeholder: A description of the actual behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      placeholder: A description of the expected outcome.
    validations:
      required: true

  - type: input
    attributes:
      label: twilio-ruby version
      description: Specify the version of the twilio-ruby helper library you are using.
      placeholder: e.g., 7.4.1
    validations:
      required: true

  - type: input
    attributes:
      label: Ruby version
      description: Specify the version of Ruby you are using.
      placeholder: e.g., 2.7.2
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs or error messages
      description: Provide relevant logs or error messages (if any).
      placeholder: "Error: Something went wrong..."

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any additional
