##
# This code was generated by
# \ / _    _  _|   _  _
#  | (_)\/(_)(_|\/| |(/_  v1.0.0
#       /       /
#
# frozen_string_literal: true

module Twilio
  module REST
    class Conversations < Domain
      ##
      # Initialize the Conversations Domain
      def initialize(twilio)
        super

        @base_url = 'https://conversations.twilio.com'
        @host = 'conversations.twilio.com'
        @port = 443

        # Versions
        @v1 = nil
      end

      ##
      # Version v1 of conversations
      def v1
        @v1 ||= V1.new self
      end

      ##
      # @param [String] sid A 34 character string that uniquely identifies this
      #   resource.
      # @return [Twilio::REST::Conversations::V1::ConversationInstance] if sid was passed.
      # @return [Twilio::REST::Conversations::V1::ConversationList]
      def conversations(sid=:unset)
        self.v1.conversations(sid)
      end

      ##
      # @return [Twilio::REST::Conversations::V1::WebhookInstance]
      def webhooks
        self.v1.webhooks()
      end

      ##
      # Provide a user friendly representation
      def to_s
        '#<Twilio::REST::Conversations>'
      end
    end
  end
end