##
#    This code was generated by
#    ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
#     |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
#     |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
#
#    Twilio Memory API
#    APIs for managing memory stores, profiles, and conversational intelligence capabilities.
#
#    NOTE: This class is auto generated by OpenAPI Generator.
#    https://openapi-generator.tech
#    Do not edit the class manually.
#


module Twilio
    module REST
        class Memory < MemoryBase
            class V1 < Version
                class IdentityResolutionSettingList < ListResource
                
                    class IdentityResolutionSettingsCore
                            # @param [identifier_configs]: [Array<IdentityResolutionSettingList.IdentifierConfig>] List of identifier types and their resolution settings.
                            # @param [matching_rules]: [Array<String>] Priority list of identifiers to locate profiles to apply new data to, or for determining if two existing profiles should merge.   Individual rules are evaluated with `OR` logic between them, meaning that satisfying any single rule will trigger a match. Each rule is a single identifier type; compound rules are not supported.  Rules are evaluated in order. - If no rule matches against existing profiles, a new profile will be created.  - If a rule matches to a single existing profile, the profile will be updated.  - If a rule matches to multiple existing profiles, those existing profiles will be merged.
                        attr_accessor :identifier_configs, :matching_rules
                        def initialize(payload)
                                @identifier_configs = payload["identifier_configs"]
                                @matching_rules = payload["matching_rules"]
                        end
                        def to_json(options = {})
                        {
                                "identifierConfigs": @identifier_configs,
                                "matchingRules": @matching_rules,
                        }.to_json(options)
                        end
                    end


                    ##
                    # Initialize the IdentityResolutionSettingList
                    # @param [Version] version Version that contains the resource
                    # @return [IdentityResolutionSettingList] IdentityResolutionSettingList
                    def initialize(version, store_id: nil)
                        
                        apiV1Version = ApiV1Version.new version.domain, version
                        super(apiV1Version)
                        # Path Solution
                        @solution = { store_id: store_id }
                        @uri = "/ControlPlane/Stores/#{@solution[:store_id]}/IdentityResolutionSettings"
                        
                    end
                    ##
                    # Fetch the IdentityResolutionSettingInstance
                    # @return [IdentityResolutionSettingInstance] Fetched IdentityResolutionSettingInstance
                    def fetch

                        headers = Twilio::Values.of({'Content-Type' => 'application/x-www-form-urlencoded', })
                        
                        
                        
                        
                        
                        payload = @version.fetch('GET', @uri, headers: headers)
                        IdentityResolutionSettingInstance.new(
                            @version,
                            payload,
                            store_id: @solution[:store_id],
                        )
                    end

                    ##
                    # Fetch the IdentityResolutionSettingInstanceMetadata
                    # @return [IdentityResolutionSettingInstance] Fetched IdentityResolutionSettingInstance
                    def fetch_with_metadata

                        headers = Twilio::Values.of({'Content-Type' => 'application/x-www-form-urlencoded', })
                        
                        
                        
                        
                        
                        response = @version.fetch_with_metadata('GET', @uri, headers: headers)
                        identity_resolution_setting_instance = IdentityResolutionSettingInstance.new(
                            @version,
                            response.body,
                            store_id: @solution[:store_id],
                        )
                        IdentityResolutionSettingInstanceMetadata.new(
                            @version,
                            identity_resolution_setting_instance,
                            response.headers,
                            response.status_code
                        )
                    end

                    ##
                    # Update the IdentityResolutionSettingInstance
                    # @param [String] if_match Allows for optimistic concurrency control by making the request conditional. Server will only act if the resource's current Entity Tag (ETag) matches the one provided, preventing accidental overwrites.
                    # @param [IdentityResolutionSettingsCore] identity_resolution_settings_core 
                    # @return [IdentityResolutionSettingInstance] Updated IdentityResolutionSettingInstance
                    def update(
                      if_match: :unset,
                      identity_resolution_settings_core: nil
                    )

                        headers = Twilio::Values.of({'Content-Type' => 'application/x-www-form-urlencoded', 'If-Match' => if_match, })
                        headers['Content-Type'] = 'application/json'
                        
                        
                        
                        
                        payload = @version.update('PUT', @uri, headers: headers, data: identity_resolution_settings_core.to_json)
                        IdentityResolutionSettingInstance.new(
                            @version,
                            payload,
                            store_id: @solution[:store_id],
                        )
                    end

                    ##
                    # Update the IdentityResolutionSettingInstanceMetadata
                    # @param [String] if_match Allows for optimistic concurrency control by making the request conditional. Server will only act if the resource's current Entity Tag (ETag) matches the one provided, preventing accidental overwrites.
                    # @param [IdentityResolutionSettingsCore] identity_resolution_settings_core 
                    # @return [IdentityResolutionSettingInstance] Updated IdentityResolutionSettingInstance
                    def update_with_metadata(
                      if_match: :unset,
                    identity_resolution_settings_core: nil
                    )

                        headers = Twilio::Values.of({'Content-Type' => 'application/x-www-form-urlencoded', 'If-Match' => if_match, })
                        headers['Content-Type'] = 'application/json'
                        
                        
                        
                        
                        response = @version.update_with_metadata('PUT', @uri, headers: headers, data: identity_resolution_settings_core.to_json)
                        identity_resolution_setting_instance = IdentityResolutionSettingInstance.new(
                            @version,
                            response.body,
                            store_id: @solution[:store_id],
                        )
                        IdentityResolutionSettingInstanceMetadata.new(
                            @version,
                            identity_resolution_setting_instance,
                            response.headers,
                            response.status_code
                        )
                    end

                


                    # Provide a user friendly representation
                    def to_s
                        '#<Twilio.Memory.V1.IdentityResolutionSettingList>'
                    end
                end

                class IdentityResolutionSettingPage < TokenPage
                    ##
                    # Initialize the IdentityResolutionSettingPage
                    # @param [Version] version Version that contains the resource
                    # @param [Response] response Response from the API
                    # @param [Hash] solution Path solution for the resource
                    # @return [IdentityResolutionSettingPage] IdentityResolutionSettingPage
                    def initialize(version, response, solution)
                        
                        apiV1Version = ApiV1Version.new version.domain, version
                        super(apiV1Version, response)

                        # Path Solution
                        @solution = solution
                    end

                    ##
                    # Build an instance of IdentityResolutionSettingInstance
                    # @param [Hash] payload Payload response from the API
                    # @return [IdentityResolutionSettingInstance] IdentityResolutionSettingInstance
                    def get_instance(payload)
                        IdentityResolutionSettingInstance.new(@version, payload, store_id: @solution[:store_id])
                    end

                    ##
                    # Provide a user friendly representation
                    def to_s
                        '<Twilio.Memory.V1.IdentityResolutionSettingPage>'
                    end
                end

                class IdentityResolutionSettingInstance < InstanceResource
                    ##
                    # Initialize the IdentityResolutionSettingInstance
                    # @param [Version] version Version that contains the resource
                    # @param [Hash] payload payload that contains response from Twilio
                    # @param [String] account_sid The SID of the
                    #   {Account}[https://www.twilio.com/docs/iam/api/account] that created this IdentityResolutionSetting
                    #   resource.
                    # @param [String] sid The SID of the Call resource to fetch.
                    # @return [IdentityResolutionSettingInstance] IdentityResolutionSettingInstance
                    def initialize(version, payload , store_id: nil)
                        
                        apiV1Version = ApiV1Version.new version.domain, version
                        super(apiV1Version)
                        
                        # Marshaled Properties
                        @properties = { 
                            'identifier_configs' => payload['identifier_configs'],
                            'matching_rules' => payload['matching_rules'],
                            'version' => payload['version'] == nil ? payload['version'] : payload['version'].to_i,
                            'message' => payload['message'],
                            'status_url' => payload['status_url'],
                        }
                    end

                    
                    ##
                    # @return [Array<IdentifierConfig>] List of identifier types and their resolution settings.
                    def identifier_configs
                        @properties['identifier_configs']
                    end
                    
                    ##
                    # @return [Array<String>] Priority list of identifiers to locate profiles to apply new data to, or for determining if two existing profiles should merge.   Individual rules are evaluated with `OR` logic between them, meaning that satisfying any single rule will trigger a match. Each rule is a single identifier type; compound rules are not supported.  Rules are evaluated in order. - If no rule matches against existing profiles, a new profile will be created.  - If a rule matches to a single existing profile, the profile will be updated.  - If a rule matches to multiple existing profiles, those existing profiles will be merged.
                    def matching_rules
                        @properties['matching_rules']
                    end
                    
                    ##
                    # @return [String] The current version number of the Identity Resolution Settings. Incremented on each successful update.
                    def version
                        @properties['version']
                    end
                    
                    ##
                    # @return [String] 
                    def message
                        @properties['message']
                    end
                    
                    ##
                    # @return [String] URI to check operation status.
                    def status_url
                        @properties['status_url']
                    end
                    
                    ##
                    # Provide a user friendly representation
                    def to_s
                        "<Twilio.Memory.V1.IdentityResolutionSettingInstance>"
                    end

                    ##
                    # Provide a detailed, user friendly representation
                    def inspect
                        "<Twilio.Memory.V1.IdentityResolutionSettingInstance>"
                    end
                end

            end
        end
    end
end
