##
#    This code was generated by
#    ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
#     |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
#     |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
#
#    Conversation Orchestrator
#    Manage configurations, conversations, participants, and communications. Create configurations to define capture rules and channel settings, then use conversations to group related communications.
#
#    NOTE: This class is auto generated by OpenAPI Generator.
#    https://openapi-generator.tech
#    Do not edit the class manually.
#


module Twilio
    module REST
        class Conversations < ConversationsBase
            class V2 < Version
                class CommunicationList < ListResource
                
                    class ContentTranscriptionTranscription
                            # @param [channel]: [String] 
                            # @param [confidence]: [Float] 
                            # @param [engine]: [String] 
                        attr_accessor :channel, :confidence, :engine
                        def initialize(payload)
                                @channel = payload["channel"]
                                @confidence = payload["confidence"]
                                @engine = payload["engine"]
                        end
                        def to_json(options = {})
                        {
                                "channel": @channel,
                                "confidence": @confidence,
                                "engine": @engine,
                        }.to_json(options)
                        end
                    end

                    class ConversationsV2ContentTranscriptionTranscription
                            # @param [channel]: [Integer] Audio channel identifier (0 for inbound, 1 for outbound).
                            # @param [confidence]: [Float] Overall confidence score for the transcription (0.0-1.0).
                            # @param [engine]: [String] Transcription engine used.
                            # @param [words]: [Array<ConversationsV2ContentTranscriptionTranscriptionWords>] Word-level transcription data with timing information.
                        attr_accessor :channel, :confidence, :engine, :words
                        def initialize(payload)
                                @channel = payload["channel"]
                                @confidence = payload["confidence"]
                                @engine = payload["engine"]
                                @words = payload["words"]
                        end
                        def to_json(options = {})
                        {
                                "channel": @channel,
                                "confidence": @confidence,
                                "engine": @engine,
                                "words": @words,
                        }.to_json(options)
                        end
                    end

                    class ConversationsV2ContentTranscriptionTranscriptionWords
                            # @param [text]: [String] The transcribed word.
                            # @param [start_time]: [Time] Start timestamp of this word.
                            # @param [end_time]: [Time] End timestamp of this word.
                        attr_accessor :text, :start_time, :end_time
                        def initialize(payload)
                                @text = payload["text"]
                                @start_time = payload["start_time"]
                                @end_time = payload["end_time"]
                        end
                        def to_json(options = {})
                        {
                                "text": @text,
                                "startTime": @start_time,
                                "endTime": @end_time,
                        }.to_json(options)
                        end
                    end

                    class CreateCommunicationInConversationRequest
                            # @param [author]: [CommunicationList.CreateCommunicationInConversationRequestAuthor] 
                            # @param [content]: [CommunicationList.CreateCommunicationInConversationRequestContent] 
                            # @param [channel_id]: [String] 
                            # @param [recipients]: [Array<CommunicationList.CreateCommunicationInConversationRequestRecipients>] 
                            # @param [occurred_at]: [Time] Timestamp when this Communication occurred. If omitted, the server uses the current time.
                        attr_accessor :author, :content, :channel_id, :recipients, :occurred_at
                        def initialize(payload)
                                @author = payload["author"]
                                @content = payload["content"]
                                @channel_id = payload["channel_id"]
                                @recipients = payload["recipients"]
                                @occurred_at = payload["occurred_at"]
                        end
                        def to_json(options = {})
                        {
                                "author": @author,
                                "content": @content,
                                "channelId": @channel_id,
                                "recipients": @recipients,
                                "occurredAt": @occurred_at,
                        }.to_json(options)
                        end
                    end

                    class CreateCommunicationInConversationRequestAuthor
                            # @param [address]: [String] 
                            # @param [channel]: [String] Channel type for a Communication address.
                            # @param [participant_id]: [String] 
                        attr_accessor :address, :channel, :participant_id
                        def initialize(payload)
                                @address = payload["address"]
                                @channel = payload["channel"]
                                @participant_id = payload["participant_id"]
                        end
                        def to_json(options = {})
                        {
                                "address": @address,
                                "channel": @channel,
                                "participantId": @participant_id,
                        }.to_json(options)
                        end
                    end

                    class CreateCommunicationInConversationRequestContent
                            # @param [type]: [String] 
                            # @param [text]: [String] 
                            # @param [transcription]: [CommunicationList.ContentTranscriptionTranscription] 
                        attr_accessor :type, :text, :transcription
                        def initialize(payload)
                                @type = payload["type"]
                                @text = payload["text"]
                                @transcription = payload["transcription"]
                        end
                        def to_json(options = {})
                        {
                                "type": @type,
                                "text": @text,
                                "transcription": @transcription,
                        }.to_json(options)
                        end
                    end

                    class CreateCommunicationInConversationRequestRecipients
                            # @param [address]: [String] 
                            # @param [channel]: [String] Channel type for a Communication address.
                            # @param [participant_id]: [String] 
                        attr_accessor :address, :channel, :participant_id
                        def initialize(payload)
                                @address = payload["address"]
                                @channel = payload["channel"]
                                @participant_id = payload["participant_id"]
                        end
                        def to_json(options = {})
                        {
                                "address": @address,
                                "channel": @channel,
                                "participantId": @participant_id,
                        }.to_json(options)
                        end
                    end


                    ##
                    # Initialize the CommunicationList
                    # @param [Version] version Version that contains the resource
                    # @return [CommunicationList] CommunicationList
                    def initialize(version, conversation_id: nil)
                        
                        apiV1Version = ApiV1Version.new version.domain, version
                        super(apiV1Version)
                        # Path Solution
                        @solution = { conversation_id: conversation_id }
                        @uri = "/Conversations/#{@solution[:conversation_id]}/Communications"
                        
                    end
                    ##
                    # Create the CommunicationInstance
                    # @param [CreateCommunicationInConversationRequest] create_communication_in_conversation_request 
                    # @return [CommunicationInstance] Created CommunicationInstance
                    def create(create_communication_in_conversation_request: :unset
                    )

                        headers = Twilio::Values.of({'Content-Type' => 'application/x-www-form-urlencoded', })
                        headers['Content-Type'] = 'application/json'
                        
                        
                        
                        
                        payload = @version.create('POST', @uri, headers: headers, data: create_communication_in_conversation_request.to_json)
                        CommunicationInstance.new(
                            @version,
                            payload,
                            conversation_id: @solution[:conversation_id],
                        )
                    end

                    ##
                    # Create the CommunicationInstanceMetadata
                    # @param [CreateCommunicationInConversationRequest] create_communication_in_conversation_request 
                    # @return [CommunicationInstance] Created CommunicationInstance
                    def create_with_metadata(create_communication_in_conversation_request: :unset
                    )

                        headers = Twilio::Values.of({'Content-Type' => 'application/x-www-form-urlencoded', })
                        headers['Content-Type'] = 'application/json'
                        
                        
                        
                        
                        response = @version.create_with_metadata('POST', @uri, headers: headers, data: create_communication_in_conversation_request.to_json)
                        communication_instance = CommunicationInstance.new(
                            @version,
                            response.body,
                            conversation_id: @solution[:conversation_id],
                        )
                        CommunicationInstanceMetadata.new(
                            @version,
                            communication_instance,
                            response.headers,
                            response.status_code
                        )
                    end

                
                    ##
                    # Lists CommunicationInstance records from the API as a list.
                    # Unlike stream(), this operation is eager and will load `limit` records into
                    # memory before returning.
                    # @param [String] channel_id Resource identifier to filter communications
                    # @param [String] page_token Page token for pagination
                    # @param [Integer] limit Upper limit for the number of records to return. stream()
                    #    guarantees to never return more than limit.  Default is no limit
                    # @param [Integer] page_size Number of records to fetch per request, when
                    #    not set will use the default value of 50 records.  If no page_size is defined
                    #    but a limit is defined, stream() will attempt to read the limit with the most
                    #    efficient page size, i.e. min(limit, 1000)
                    # @return [Array] Array of up to limit results
                    def list(channel_id: :unset, page_token: :unset, limit: nil, page_size: nil)
                        self.stream(
                            channel_id: channel_id,
                            page_token: page_token,
                            limit: limit,
                            page_size: page_size
                        ).entries
                    end

                    ##
                    # Streams Instance records from the API as an Enumerable.
                    # This operation lazily loads records as efficiently as possible until the limit
                    # is reached.
                    # @param [String] channel_id Resource identifier to filter communications
                    # @param [String] page_token Page token for pagination
                    # @param [Integer] limit Upper limit for the number of records to return. stream()
                    #    guarantees to never return more than limit.  Default is no limit
                    # @param [Integer] page_size Number of records to fetch per request, when
                    #    not set will use the default value of 50 records.  If no page_size is defined
                    #    but a limit is defined, stream() will attempt to read the limit with the most
                    #    efficient page size, i.e. min(limit, 1000)
                    # @return [Enumerable] Enumerable that will yield up to limit results
                    def stream(channel_id: :unset, page_token: :unset, limit: nil, page_size: nil)
                        limits = @version.read_limits(limit, page_size)

                        page = self.page(
                            channel_id: channel_id,
                            page_token: page_token,
                            page_size: limits[:page_size], )

                        return [].each if page.nil?

                        result = @version.stream(page, limit: limits[:limit], page_limit: limits[:page_limit])
                        return [].each if result.nil?
                        result
                    end

                    ##
                    # Lists CommunicationPageMetadata records from the API as a list.
                      # @param [String] channel_id Resource identifier to filter communications
                      # @param [String] page_token Page token for pagination
                    # @param [Integer] limit Upper limit for the number of records to return. stream()
                    #    guarantees to never return more than limit.  Default is no limit
                    # @param [Integer] page_size Number of records to fetch per request, when
                    #    not set will use the default value of 50 records.  If no page_size is defined
                    #    but a limit is defined, stream() will attempt to read the limit with the most
                    #    efficient page size, i.e. min(limit, 1000)
                    # @return [Array] Array of up to limit results
                    def list_with_metadata(channel_id: :unset, page_token: :unset, limit: nil, page_size: nil)
                        limits = @version.read_limits(limit, page_size)
                        params = Twilio::Values.of({
                            'channelId' => channel_id,
                            'pageToken' => page_token,
                            
                            'PageSize' => limits[:page_size],
                        });
                        headers = Twilio::Values.of({})

                        response = @version.page('GET', @uri, params: params, headers: headers)

                        CommunicationPageMetadata.new(@version, response, @solution, limits[:limit])
                    end

                    ##
                    # When passed a block, yields CommunicationInstance records from the API.
                    # This operation lazily loads records as efficiently as possible until the limit
                    # is reached.
                    def each
                        limits = @version.read_limits

                        page = self.page(page_size: limits[:page_size], )

                        return [].each if page.nil?

                        result = @version.stream(page,
                            limit: limits[:limit],
                            page_limit: limits[:page_limit])
                        return [].each if result.nil?
                        result.each {|x| yield x}
                    end

                    ##
                    # Retrieve a single page of CommunicationInstance records from the API.
                    # Request is executed immediately.
                    # @param [String] channel_id Resource identifier to filter communications
                    # @param [String] page_token Page token for pagination
                    
                    # @return [Page] Page of CommunicationInstance
                    def page(channel_id: :unset, page_token: :unset, page_size: :unset)
                        params = Twilio::Values.of({
                            'channelId' => channel_id,
                            'pageToken' => page_token,
                                                        'PageSize' => page_size,
                        })
                        headers = Twilio::Values.of({})
                        
                        

                        response = @version.page('GET', @uri, params: params, headers: headers)

                        CommunicationPage.new(@version, response, @solution)
                    end

                    ##
                    # Retrieve a single page of CommunicationInstance records from the API.
                    # Request is executed immediately.
                    # @param [String] target_url API-generated URL for the requested results page
                    # @return [Page] Page of CommunicationInstance
                    def get_page(target_url)
                        response = @version.domain.request(
                            'GET',
                            target_url
                        )
                    CommunicationPage.new(@version, response, @solution)
                    end
                    


                    # Provide a user friendly representation
                    def to_s
                        '#<Twilio.Conversations.V2.CommunicationList>'
                    end
                end


                class CommunicationContext < InstanceContext
                    ##
                    # Initialize the CommunicationContext
                    # @param [Version] version Version that contains the resource
                    # @param [String] conversation_id 
                    # @param [String] id 
                    # @return [CommunicationContext] CommunicationContext
                    def initialize(version, conversation_id, id)
                        
                        apiV1Version = ApiV1Version.new version.domain, version
                        super(apiV1Version)

                        # Path Solution
                        @solution = { conversation_id: conversation_id, id: id,  }
                        @uri = "/Conversations/#{@solution[:conversation_id]}/Communications/#{@solution[:id]}"

                        
                    end
                    ##
                    # Fetch the CommunicationInstance
                    # @return [CommunicationInstance] Fetched CommunicationInstance
                    def fetch

                        headers = Twilio::Values.of({'Content-Type' => 'application/x-www-form-urlencoded', })
                        
                        
                        
                        
                        
                        payload = @version.fetch('GET', @uri, headers: headers)
                        CommunicationInstance.new(
                            @version,
                            payload,
                            conversation_id: @solution[:conversation_id],
                            id: @solution[:id],
                        )
                    end

                    ##
                    # Fetch the CommunicationInstanceMetadata
                    # @return [CommunicationInstance] Fetched CommunicationInstance
                    def fetch_with_metadata

                        headers = Twilio::Values.of({'Content-Type' => 'application/x-www-form-urlencoded', })
                        
                        
                        
                        
                        
                        response = @version.fetch_with_metadata('GET', @uri, headers: headers)
                        communication_instance = CommunicationInstance.new(
                            @version,
                            response.body,
                            conversation_id: @solution[:conversation_id],
                            id: @solution[:id],
                        )
                        CommunicationInstanceMetadata.new(
                            @version,
                            communication_instance,
                            response.headers,
                            response.status_code
                        )
                    end


                    ##
                    # Provide a user friendly representation
                    def to_s
                        context = @solution.map{|k, v| "#{k}: #{v}"}.join(',')
                        "#<Twilio.Conversations.V2.CommunicationContext #{context}>"
                    end

                    ##
                    # Provide a detailed, user friendly representation
                    def inspect
                        context = @solution.map{|k, v| "#{k}: #{v}"}.join(',')
                        "#<Twilio.Conversations.V2.CommunicationContext #{context}>"
                    end
                end

                class CommunicationInstanceMetadata <  InstanceResourceMetadata
                    ##
                    # Initializes a new CommunicationInstanceMetadata.
                    # @param [Version] version Version that contains the resource
                    # @param [}CommunicationInstance] communication_instance The instance associated with the metadata.
                    # @param [Hash] headers Header object with response headers.
                    # @param [Integer] status_code The HTTP status code of the response.
                    # @return [CommunicationInstanceMetadata] The initialized instance with metadata.
                    def initialize(version, communication_instance, headers, status_code)
                        super(version, headers, status_code)
                        @communication_instance = communication_instance
                    end

                    def communication
                        @communication_instance
                    end

                    def headers
                        @headers
                    end

                    def status_code
                        @status_code
                    end

                    def to_s
                      "<Twilio.Api.V2010.CommunicationInstanceMetadata status=#{@status_code}>"
                    end
                end

                class CommunicationListResponse < InstanceListResource
                    # @param [Array<CommunicationInstance>] instance
                    # @param [Hash{String => Object}] headers
                    # @param [Integer] status_code
                    def initialize(version, payload, key)
                       @communication_instance = payload.body[key].map do |data|
                        CommunicationInstance.new(version, data)
                       end
                       @headers = payload.headers
                       @status_code = payload.status_code
                    end

                      def communication_instance
                          @instance
                      end
                  end

                class CommunicationPage < TokenPage
                    ##
                    # Initialize the CommunicationPage
                    # @param [Version] version Version that contains the resource
                    # @param [Response] response Response from the API
                    # @param [Hash] solution Path solution for the resource
                    # @return [CommunicationPage] CommunicationPage
                    def initialize(version, response, solution)
                        
                        apiV1Version = ApiV1Version.new version.domain, version
                        super(apiV1Version, response)

                        # Path Solution
                        @solution = solution
                    end

                    ##
                    # Build an instance of CommunicationInstance
                    # @param [Hash] payload Payload response from the API
                    # @return [CommunicationInstance] CommunicationInstance
                    def get_instance(payload)
                        CommunicationInstance.new(@version, payload, conversation_id: @solution[:conversation_id])
                    end

                    ##
                    # Provide a user friendly representation
                    def to_s
                        '<Twilio.Conversations.V2.CommunicationPage>'
                    end
                end

                class CommunicationPageMetadata < PageMetadata
                    attr_reader :communication_page

                    def initialize(version, response, solution, limit)
                        super(version, response)
                        @communication_page = []
                        @limit = limit
                        key = get_key(response.body)
                        records = 0
                        while( limit != :unset && records < limit )
                            @communication_page << CommunicationListResponse.new(version, @payload, key, limit - records)
                            @payload = self.next_page
                            break unless @payload
                            records += (@payload.body[key] || []).size
                        end
                        # Path Solution
                        @solution = solution
                    end

                    def each
                        @communication_page.each do |record|
                          yield record
                        end
                    end

                    def to_s
                      '<Twilio::REST::Conversations::V2PageMetadata>';
                    end
                end
                class CommunicationListResponse < InstanceListResource

                    # @param [Array<CommunicationInstance>] instance
                    # @param [Hash{String => Object}] headers
                    # @param [Integer] status_code
                    def initialize(version, payload, key, limit = :unset)
                      data_list = payload.body[key]  || []
                      if limit != :unset
                        data_list = data_list[0, limit]
                      end
                      @communication = data_list.map do |data|
                        CommunicationInstance.new(version, data)
                      end
                      @headers = payload.headers
                      @status_code = payload.status_code
                    end

                    def communication
                        @communication
                    end

                    def headers
                      @headers
                    end

                    def status_code
                      @status_code
                    end
                end

                class CommunicationInstance < InstanceResource
                    ##
                    # Initialize the CommunicationInstance
                    # @param [Version] version Version that contains the resource
                    # @param [Hash] payload payload that contains response from Twilio
                    # @param [String] account_sid The SID of the
                    #   {Account}[https://www.twilio.com/docs/iam/api/account] that created this Communication
                    #   resource.
                    # @param [String] sid The SID of the Call resource to fetch.
                    # @return [CommunicationInstance] CommunicationInstance
                    def initialize(version, payload , conversation_id: nil, id: nil)
                        
                        apiV1Version = ApiV1Version.new version.domain, version
                        super(apiV1Version)
                        
                        # Marshaled Properties
                        @properties = { 
                            'id' => payload['id'],
                            'conversation_id' => payload['conversation_id'],
                            'account_id' => payload['account_id'],
                            'author' => payload['author'],
                            'content' => payload['content'],
                            'channel_id' => payload['channel_id'],
                            'resource_id' => payload['resource_id'],
                            'recipients' => payload['recipients'],
                            'created_at' => Twilio.deserialize_iso8601_datetime(payload['created_at']),
                            'updated_at' => Twilio.deserialize_iso8601_datetime(payload['updated_at']),
                            'occurred_at' => Twilio.deserialize_iso8601_datetime(payload['occurred_at']),
                        }

                        # Context
                        @instance_context = nil
                        @params = { 'conversation_id' => conversation_id  || @properties['conversation_id']  ,'id' => id  || @properties['id']  , }
                    end

                    ##
                    # Generate an instance context for the instance, the context is capable of
                    # performing various actions.  All instance actions are proxied to the context
                    # @return [CommunicationContext] CallContext for this CallInstance
                    def context
                        unless @instance_context
                            @instance_context = CommunicationContext.new(@version , @params['conversation_id'], @params['id'])
                        end
                        @instance_context
                    end
                    
                    ##
                    # @return [String] Communication ID.
                    def id
                        @properties['id']
                    end
                    
                    ##
                    # @return [String] Conversation ID.
                    def conversation_id
                        @properties['conversation_id']
                    end
                    
                    ##
                    # @return [String] Account ID.
                    def account_id
                        @properties['account_id']
                    end
                    
                    ##
                    # @return [ConversationsV2ParticipantAddress] 
                    def author
                        @properties['author']
                    end
                    
                    ##
                    # @return [ListCommunicationByConversation200ResponseCommunicationsContent] 
                    def content
                        @properties['content']
                    end
                    
                    ##
                    # @return [String] Channel-specific reference ID.
                    def channel_id
                        @properties['channel_id']
                    end
                    
                    ##
                    # @return [String] External resource identifier for this Communication (e.g. MessageSid for SMS/RCS/WhatsApp, TranscriptionSid + MessageIndex for Voice). When set, used for Communication deduplication/uniqueness within a Conversation.
                    def resource_id
                        @properties['resource_id']
                    end
                    
                    ##
                    # @return [Array<ListCommunicationByConversation200ResponseCommunicationsRecipients>] Communication recipients.
                    def recipients
                        @properties['recipients']
                    end
                    
                    ##
                    # @return [Time] Timestamp when this Communication was created.
                    def created_at
                        @properties['created_at']
                    end
                    
                    ##
                    # @return [Time] Timestamp when this Communication was last updated.
                    def updated_at
                        @properties['updated_at']
                    end
                    
                    ##
                    # @return [Time] ISO 8601 timestamp when the communication occurred.
                    def occurred_at
                        @properties['occurred_at']
                    end
                    
                    ##
                    # Fetch the CommunicationInstance
                    # @return [CommunicationInstance] Fetched CommunicationInstance
                    def fetch

                        context.fetch
                    end

                    ##
                    # Provide a user friendly representation
                    def to_s
                        values = @params.map{|k, v| "#{k}: #{v}"}.join(" ")
                        "<Twilio.Conversations.V2.CommunicationInstance #{values}>"
                    end

                    ##
                    # Provide a detailed, user friendly representation
                    def inspect
                        values = @properties.map{|k, v| "#{k}: #{v}"}.join(" ")
                        "<Twilio.Conversations.V2.CommunicationInstance #{values}>"
                    end
                end

            end
        end
    end
end
